name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      from_repo:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Repo test
        run: ls
